python src/pretrain.py\
       --resnet resnet18\
       --n_hidden 512\
       --learning_rate 1e-4\
       --weight_decay 1e-3\
       --batch_size 32\
       --data_root "/work/t405/T40511/work/vehvilt2/lrw1"\
       --workers 16\
       --weight_hist 0\
       --max_epochs 100\
       --description "just testing"\
       --fast_dev_run 0
